#' @title
#' Extract a single tibble from a REDCapTidieR supertibble
#'
#' @description
#' Take a supertibble generated with \code{read_redcap_tidy()}
#' and return one of its tibbles.
#'
#' @details
#' This function makes it easy to extract a single instrument's data from a
#' REDCapTidieR supertibble.
#'
#' @returns A \code{tibble}
#'
#' @param .data A tibble generated by \code{read_redcap_tidy()}. Required.
#' @param tbl The \code{form_name} to extract. Required.
#'
#' @importFrom checkmate assert_character
#' @importFrom rlang .data
#'
#' @examples
#' \dontrun{
#' redcap_uri <- Sys.getenv("REDCAP_URI")
#' token <- Sys.getenv("REDCAP_TOKEN")
#'
#' out <- read_redcap_tidy(
#'           redcap_uri,
#'           token,
#'           raw_or_label = "label"
#'         )
#'
#'  extract_table(out, "sample_form_name")
#' }
#'
#' @export

extract_table <- function(.data,
                          tbl) {
  # Check tbl is valid ----
  assert_character(all_of(tbl))

  if (length(all_of(tbl)) > 1) {
    stop("Only one table may be supplied.")
  }

  # Extract specified table ----
  out <- extract_tables(.data, tbls = all_of(tbl))[[1]]

  out
}


#' Extract one or more tibbles from a REDCapTidieR supertibble
#'
#' @description
#' Take a supertibble generated with \code{read_redcap_tidy()}
#' and return a named list of tibbles.
#'
#' @details
#' This function makes it easy to extract a multiple instrument's data from a
#' REDCapTidieR supertibble into a named list. Specifying instruments using
#' \code{tidyselect} semantics such as \code{starts_with()}
#' or \code{ends_with()} is supported.
#'
#' @returns A named list of \code{tibble}s
#'
#' @param .data A tibble generated by \code{read_redcap_tidy()}. Required.
#' @param tbls A vector of \code{form_name}s or a tidy selector. Default is
#' \code{everything()}.
#'
#' @importFrom rlang .data enquo
#' @importFrom dplyr select
#' @importFrom tidyselect eval_select everything
#' @importFrom tidyr pivot_wider
#' @importFrom purrr map pluck
#'
#' @examples
#' \dontrun{
#' redcap_uri <- Sys.getenv("REDCAP_URI")
#' token <- Sys.getenv("REDCAP_TOKEN")
#'
#' out <- read_redcap_tidy(
#'           redcap_uri,
#'           token,
#'           raw_or_label = "label"
#'         )
#'
#'  extract_tables(out, c("sample_form_name1", "sample_form_name2"))
#'  extract_tables(out, everything())
#'  extract_tables(out, starts_with("demographics"))
#' }
#'
#' @export

extract_tables <- function(.data,
                           tbls = everything()) {

  # Extract specified table ----
  # Pass tbls as an expression for enquosure
  tbls <- enquo(tbls)

  out <- .data %>%
    select(-.data$structure) %>%
    pivot_wider(names_from = .data$redcap_form_name,
                values_from = .data$redcap_data)

  out <- out[eval_select(tbls, data = out)]

  out %>%
    map(.f = ~pluck(.)[[1]])
}
